---
title: "An introduction to R"
output: 
  html_document:
    toc: no
---

\  

### Course Introduction

Welcome to the [QUADRAT](https://www.quadrat.ac.uk/){target='_blank'} and [SUPER](https://superdtp.st-andrews.ac.uk/){target='_blank'} DTP *Introduction to R* training course. Over the three days of this course we aim to introduce you to using R, an interactive environment for statistical computing. R in itself is not difficult to learn, but just like any new language the initial learning curve can be a little steep and you will need to use it frequently otherwise it’s easy to forget. 

A few notes about this course. We have tried to simplify the content of this course as much as possible and have based it on 15 years experience teaching (and learning!) R. It is not intended as an introductory statistics course, although we will be using some basic statistics to highlight some of R’s capabilities. Our aim is to help you climb the initial learning curve and provide you with the basic skills to enable you to further your experience in using R. We have included a number of practical [exercises](exercises.html) for you to work through during the course and encourage you complete these in your own time - you certainly won’t learn how to use R by watching other people do it. 

See this [FAQ](FAQ.html) for information about how to use this site and some things you need to do before the course starts.