---
title: 'Lectures'
output: 
  html_document:
    toc: false
---
```{r, include=FALSE}
library(htmltools)
suppressPackageStartupMessages(library(htmltools))
source('utils.R')
source('reveal.R')
```

\  

Lecture slides that we deliver during our in-person courses to help support you whilst learning R. This material should be used in conjunction with the [Introduction to R](https://alexd106.github.io/Rbook) book. 

Either tap on the slides or use your keyboard arrow keys (&#8592; &#8594;) to scroll through the slides. Press 'h' for other slide options.

\  

```{r, echo=FALSE, eval = isFALSE(show_lecture)}
cat("Lectures will be released as the course progresses")
```

\  

```{r intro-lec, echo=FALSE}
knitr::include_url('https://alexd106.github.io/Rintro_lec/Rintro_lecture#1')
```

\  

```{r data-lec, echo=FALSE}
knitr::include_url('https://alexd106.github.io/Rdata_lec/Rdata_lecture#1')
```

\  

```{r stat-lec, echo=FALSE}
knitr::include_url('https://alexd106.github.io/Rstats_lec/Rstats_lecture#1')
```

<!--
Follow the links below for pdf versions of the lecture slides.
-->
\  

```{r, reveal, echo=FALSE, eval = isTRUE(show_lecture_pdf)}
cat("Lectures will be released as the course progresses")
```


```{r, echo=FALSE, eval = isTRUE(show_lecture_pdf)}
thumbnail("Introduction to R", "images/r_lecture_thumb.png",
          "lectures/introduction_to_r_quadrat_2019.pdf")
```

```{r, echo=FALSE, eval = isTRUE(show_lecture_pdf)}
thumbnail("Data in R", "images/data_in_r_thumb.png",
          "lectures/getting_the_data_in_r.pdf")
```

```{r, echo=FALSE, eval = isTRUE(show_lecture_pdf)}
thumbnail("Simple Statistics in R", "images/stats_r_thumb.png",
          "lectures/statistics_in_r.pdf")
```
