---
title: 'Syllabus'
output: 
  html_document:
    toc: false
---

\  

The course will start at 09:30 each morning and finish at 17:00. We will break for a one hour lunch break around 12:30. However, everyone learns R in their own way and at their own pace so this syllabus should be treated as indicative rather than absolute. There will also be plenty of opportunities to take short breaks during the course and we will also have a couple of 30 minute sessions on robust and reproducible research practices. 

<!--All teaching will be held in room FN113 in the Fraser Noble building (building No. 7 on [this map](images/uoa_map.png){target="_blank"} on the old Aberdeen campus).
-->

\  

#### Tuesday 5^th^ December 2023

  - 14:00 - 15:00: Online drop-in session for software installation issues (BBcollaborate)

\  

#### Wednesday 6^th^ December 2023

  - Morning: Introduction to the course, getting to know R and RStudio ([Exercise 1](https://alexd106.github.io/QUADstatR/exercise_1.html))

  - Afternoon: Basic R operations ([Exercise 2](https://alexd106.github.io/QUADstatR/exercise_2.html))

\  

#### Thursday 7^th^ December 2023

  - Morning: Importing and manipulating dataframes ([Exercise 3](https://alexd106.github.io/QUADstatR/exercise_3.html))

  - Afternoon: Plotting data in R using base and lattice graphics ([Exercise 4](https://alexd106.github.io/QUADstatR/exercise_4.html))

\  

#### Friday 8^th^ December 2023
  - Morning: Simple statistics in R ([Exercise 5](https://alexd106.github.io/QUADstatR/exercise_5.html))

  - Afternoon: Basic programming in R (optional) or catchup ([Exercise 6](https://alexd106.github.io/QUADstatR/exercise_6.html))